language: python

install:
   - pip3 install --upgrade pip
   - pip install pytest
   - pip install stripe
   - pip install selenium
   - wget -N http://chromedriver.storage.googleapis.com/72.0.3626.7/chromedriver_linux64.zip -P /tmp
   - unzip /tmp/chromedriver_linux64.zip -d /tmp
   - rm /tmp/chromedriver_linux64.zip
   - sudo mv -f /tmp/chromedriver /usr/local/share/
   - sudo chmod +x /usr/local/share/chromedriver
   - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
   - python -m http.server 8000 &

script: 
 pytest test.py -v --tb=short
